INSERT INTO TRAINING(ID,NOMBRE,DURACION) VALUES (1, 'test 1', 11);
INSERT INTO TRAINING(ID,NOMBRE,DURACION) VALUES (2, 'test 2', 13);
INSERT INTO TRAINING(ID,NOMBRE,DURACION) VALUES (3, 'test 3', 17);
INSERT INTO TRAINING(ID,NOMBRE,DURACION) VALUES (4, 'test 4', 19);